### PR TITLE
Add new quotes to JSON file, issue number 1

### PR DESCRIPTION
**Pull request by vega-2135**
Check one of the below boxes as per your PR

- [ ] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)
- [ ] Fixes another issue #00 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] code is in uniquely-named branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 if applicable
* [ ] ask `@avats-dev` for help, in a comment below

> I'm happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** !

Thanks!

### CODE REVIEW

**Comment by vega-2135** [comment]
Add more quotes to file 200.json

**Review by avats-dev — CHANGES_REQUESTED** [review]
Hey @vega-2135 , can you rename your file as mentioned [here](https://github.com/avats-dev/motivate#contribution). Thanks :+1: 

> Feel free to ping back if you're stuck or need any help.

**Comment by vega-2135** [comment]
> Hey @vega-2135 , can you rename your file as mentioned [here](https://github.com/avats-dev/motivate#contribution). Thanks +1
> 
> > Feel free to ping back if you're stuck or need any help.

Hello, I did the change, but I'm not sure what should I do now xD, sorry this is my first pr :/.

**Comment by avats-dev** [comment]
@vega-2135 you have edited an existing file `200.json` while you need to commit a new file as mentioned here https://github.com/avats-dev/motivate#contribution. Thanks, closing this. Open a new PR with a file of your own.

**Pull request closed without merging**
