### PR TITLE
added 15 more quotes

### PR DESCRIPTION
**Pull request by anwesha-mohanty**
Check one of the below boxes as per your PR

- [x] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)
- [ ] Fixes another issue #00 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] code is in uniquely-named branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 if applicable
* [ ] ask `@avats-dev` for help, in a comment below

> I'm happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** !

Thanks!

### CODE REVIEW

**Review by avats-dev — CHANGES_REQUESTED** [review]
Hey @AdnanMuhib  , can you rename your file as mentioned [here](https://github.com/avats-dev/motivate#contribution). Thanks :+1: 
Sorry, for your inconvenience.
> Feel free to ping back if you're stuck or need any help.

**Comment by anwesha-mohanty** [comment]
> Hey @anwesha-mohanty , can you rename your file as mentioned [here](https://github.com/avats-dev/motivate#contribution). 

Yes sure! Have made the changes

**Comment by avats-dev** [comment]
Hey @anwesha-mohanty , after you make the changes, you again need to push those to your remote so that they update here as recent commit. As, this PR has not updated anything, I think you need to push those changes.

**Comment by avats-dev** [comment]
Ok, I see you have opened a new PR #79 with the changes. Thanks, managing this :tada:

**Pull request closed without merging**
