### PR TITLE
more motivational quotes

### PR DESCRIPTION
**Pull request by spacemonkey1101**
Added quotes

### CODE REVIEW

**Review by avats-dev — CHANGES_REQUESTED** [review]
Everything seems fine, nice work :tada: .
As, there is already a file `188.json`, could you rename this to `189.json` to avoid merge conflicts.

**Comment by spacemonkey1101** [comment]
I have made the changes

**Review by avats-dev — APPROVED** [review]
Looks all good now.
Thanks :tada:

**Comment by shagun25** [comment]
can i take this work?

**Comment by avats-dev** [comment]
> can i take this work?

Yes @shagun25 you can open a new PR referencing #1 or #16  . Ping back if you need any help.:+1:

**Comment by shagun25** [comment]
okay great

**Pull request merged**
