### PR TITLE
[ ] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)

### PR DESCRIPTION
**Pull request by Zubair-12**
Check one of the below boxes as per your PR

- [x] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)
- [ ] Fixes another issue #00 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] code is in uniquely-named branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 if applicable
* [ ] ask `@avats-dev` for help, in a comment below

> I'm happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** !

Thanks!

### CODE REVIEW

**Comment by Zubair-12** [comment]
Hi @avats-dev Please Review my PR. Thanks!

**Review by avats-dev — CHANGES_REQUESTED** [review]
Thanks @Zubair-12 for contributing, just need one minor fix. Can you rename your file as mentioned here https://github.com/avats-dev/motivate#contribution. 

> Sorry for inconvenience, needed to avoid merge conflicts.

**Comment by Zubair-12** [comment]
Yes I can do that. You mean from 192.json to Zubair-12.json. Am I right @avats-dev .

**Comment by avats-dev** [comment]
> Yes I can do that. You mean from 192.json to Zubair-12.json. Am I right @avats-dev .

yeah, thanks. :+1:

**Comment by Zubair-12** [comment]
Hi @avats-dev Please Review my PR. Thanks!

**Review by avats-dev — APPROVED** [review]

**Comment by avats-dev** [comment]
Thanks :+1:

**Pull request merged**
