### PR TITLE
Add New Random Inspirational Quotes

### PR DESCRIPTION
**Pull request by AdnanMuhib**
Check one of the below boxes as per your PR

- [x] Adding more quotes [issue](https://github.com/avats-dev/motivate/issues/1)
- [ ] Fixes another issue #00 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] code is in uniquely-named branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 if applicable
* [ ] ask `@avats-dev` for help, in a comment below

> I'm happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** !

Thanks!

### CODE REVIEW

**Review by avats-dev — CHANGES_REQUESTED** [review]
Hey @AdnanMuhib  , can you rename your file as mentioned [here](https://github.com/avats-dev/motivate#contribution). Thanks :+1: 

> Feel free to ping back if you're stuck or need any help.

**Comment by AdnanMuhib** [comment]
@avats-dev Renamed the file.

**Comment by avats-dev** [comment]
@AdnanMuhib you also need to change the order. `quote`  should come first and then its `author`. See other contributions for reference. Thanks

**Comment by AdnanMuhib** [comment]
done 🚀 
however, it really doesn't matter in which order JSON keys are when parsing.
I agree that order should be the same as others if we think about consistency.

**Comment by avats-dev** [comment]
Yeah @AdnanMuhib , it doesn't matters but consistency and order matters. Thanks for your contribution :tada:

**Review by avats-dev — APPROVED** [review]

**Pull request merged**
